### ISSUE TITLE
Support for linux/amd64 in mono:5.10.0.160

### ISSUE THREAD

**Issue by lcsmontiel** [mono/docker#72] opened 2018-03-20 00:38 UTC
After update of latest my build get the following error: 
no matching manifest for linux/amd64 in the manifest list entries

Was using mono:latest, after explicit set the downgrade to 5.8 it was fixing. So the error was in 5.10

**Comment by akoeplinger** [comment] 2018-03-22 13:58
I can't reproduce this here, do you still see this issue?

**Comment by akoeplinger** [comment] 2018-03-28 01:31
Closing for now as it works here, please feel free to respond if you still see it :)

**Closed by akoeplinger** 2018-03-28 01:31 UTC
