### ISSUE TITLE
/tmp folder contains two big files

### ISSUE THREAD

**Issue by MarkLie** [mono/docker#37] opened 2016-07-12 13:24 UTC
Hi community,
I was just wondering, whether the two files in the /tmp are really needed? I am concerned about the size of the image. It would be nice to remove all unnecessary files, but I am unsure whether this is the case here.

Best Regards,
Mark

**Comment by dominikhahn** [comment] 2016-07-12 13:30
LGTM👍  created a pr: https://github.com/mono/docker/pull/38

**Comment by akoeplinger** [comment] 2016-07-12 15:12
It looks like they're only in the Mono 4.4.x images. I'm asking around what might cause it, but I think removing them is fine.

**Comment by akoeplinger** [comment] 2016-07-21 18:17
Ok, so I found the root cause: those two files are leftovers from an attempt to AOT compile mscorlib.dll and mcs.exe which we do at package installation time. However, AOT compilation fails in the Mono 4.4 image and leaves those files in /tmp.

The reason is that the image doesn't have `as` (the GNU assembler) installed. This wasn't a problem in earlier versions because there was a feature which directly wrote the object file, but that was removed in https://github.com/mono/mono/commit/cc946ea5b9e3cbb020c66d8986ecd220ca7ba58c so AOT relies on `as` now.

We'll make a fix to future Mono packages so they depend on the binutils package. I'll also patch up the 4.4.x Dockerfiles to add this manually.

Thanks for the report!

**Comment by akoeplinger** [comment] 2016-07-21 18:26
Should be fixed in https://github.com/mono/docker/commit/4e1d4cc196b612bcbd8466906815bfaef1f1413e. I'll close this once I pushed to the Docker Hub (might be a few days since we're readying the Mono 4.4 service release 1 and I want to batch those two).

**Comment by akoeplinger** [comment] 2016-08-04 20:06
This is available in the Docker Hub now. Thanks again for reaching out!

**Closed by akoeplinger** 2016-08-04 20:06 UTC
Labels: bug
